package com.salesianostriana.dam.videogamesshopproject_sebastianmillan.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@Embeddable
public class LineaVentaPK implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long venta_id;
	
	@Column(columnDefinition = "bigint GENERATED BY DEFAULT AS IDENTITY")
	private Long lineaVenta_id;
	
}
